- package-lock.json
- package.json
- src/utils/codapListeners.ts
- src/utils/codapPhone.ts
- src/utils/iframe-phone.d.ts
```typescript
await createDataset("hello", [{
name: "Jason",
age: 21
}, {
name: "Rachel",
age: 25
}]);
```
```javascript
await getAllDataContexts();
```
```javascript
await getDataFromContext("Context Name");
```
```javascript
await createTable("Context Name");
```
```typescript
const [dataContexts, setDataContexts] = useState<string[]|null>(null);
// Refresh to set up connection
useEffect(() => {
refreshTables();
addCodapListener(refreshTables);
return () => removeCodapListener(refreshTables);
}, []);
async function refreshTables() {
setDataContexts(await getAllDataContexts());
}
```
> Add preliminary CODAP integration

- .eslintignore
- .eslintrc.js
- .github/workflows/node.js.yml
- .prettierignore
- .prettierrc.json
- .vscode/settings.json
- package-lock.json
- package.json
- src/Error.tsx
- src/Transformation.test.tsx
- src/Transformation.tsx
- src/index.tsx
- src/language/__tests__/integration.test.ts
- src/language/__tests__/interpret.test.ts
- src/language/__tests__/parse.test.ts
- src/language/interpret.ts
- src/language/lex.ts
- src/language/parse.ts
- src/language/parselets.ts
- src/utils/codapListeners.ts
- src/utils/codapPhone.ts
The goal of this PR is to add a few tools that make it easier for us to work on this repo:
* linting with ESlint to make sure we're following best practices and catching simple bugs
* formatting with Prettier so we don't have to worry about style convecntions
* CI with Github actions to make sure that PRs pass linting/formatting before they can be merged
> Add better tooling

- src/Error.tsx
- src/Transformation.tsx
- src/language/parselets.ts
- src/reportWebVitals.ts
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/listeners.ts
- src/utils/codapPhone/types.ts
> Complete api types rebased

- src/utils/codapPhone/index.ts
- src/utils/codapPhone/types.ts
Nice to have: give plugin a title and make it full size on startup.
> Initialize interactive frame on startup

- src/Transformation.tsx
- src/transformation-components/Sort.tsx
- src/transformations/sort.ts
Asks user for a key expression which is used to sort the table.
> Add sort transformation

- src/transformation-components/BuildColumn.tsx
- src/transformation-components/Compare.tsx
- src/transformation-components/Count.tsx
- src/transformation-components/DifferenceFrom.tsx
- src/transformation-components/Filter.tsx
- src/transformation-components/Flatten.tsx
- src/transformation-components/Fold.tsx
- src/transformation-components/GroupBy.tsx
- src/transformation-components/SelectAttributes.tsx
- src/transformation-components/Sort.tsx
- src/transformation-components/TransformColumn.tsx
- src/ui-components/AttributeSelector.tsx
- src/ui-components/ContextSelector.tsx
- src/ui-components/index.ts
This just factors out context and attribute selectors into their own components.
> Factor out context and attribute selectors

- src/transformation-components/SelectAttributes.tsx
- src/transformations/selectAttributes.ts
Adds support for indicating you want to select only the given attributes, or all attributes excluding those given. This is using the old UI components and will need to be merged with the new stuff.
> "select only" and "select all but" for select attributes

- src/Transformation.tsx
- src/transformation-components/PivotLonger.tsx
- src/transformation-components/PivotWider.tsx
- src/transformations/pivot.ts
- src/transformations/selectAttributes.ts
- src/transformations/util.ts
Adds the pivot transformations detailed [here](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html).
> add pivot longer/wider

- src/Transformation.tsx
How should we group these transformations?
Note: this is a temporary interface. We can move to a nicer one in the future.
> Add preliminary grouping of transformations

- src/utils/codapPhone/types.ts
> Trigger flow update on collection hierarchy update

- src/transformation-components/Fold.tsx
This makes the resulting attribute name in all fold transformations "\<fold type\> of \<input attribute\>", while ensuring that the name is unique. For instance, "Running Min of Age".
I like this because it handles the common case in which a user wants to name the attribute after exactly what it is doing, and so eliminates an extra step in the UI. The trouble that may come along with renaming after creating the table (and then having the changes be clobbered by a later context update) is something we should probably discuss. I think it's a broader question: to what extent do we want to allow them to mess with the dataset by hand-mutating it in intermediate stages?
Also note that this doesn't really address the idea of indicating that these aggregate columns are "snapshots" of an input …
> update aggregators to use a generated attribute name

- src/transformation-components/Compare.tsx
- src/transformation-components/Count.tsx
- src/transformation-components/DifferenceFrom.tsx
- src/transformation-components/Filter.tsx
- src/transformation-components/Fold.tsx
- src/transformation-components/GroupBy.tsx
- src/transformation-components/Join.tsx
- src/transformation-components/PivotLonger.tsx
- src/transformation-components/PivotWider.tsx
- src/transformation-components/SelectAttributes.tsx
- src/transformation-components/TransformColumn.tsx
- src/ui-components/AttributeSelector.tsx
- src/ui-components/MultiAttributeSelector.tsx
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/listeners.ts
- src/utils/hooks.ts
If an attribute gets selected and then gets deleted, the attribute selector will reset. A multi attribute selector will filter out any invalid selected attributes when they change.
> Update attribute selectors when attributes change (deleted or renamed)

- README.md
I just cut out some of the boilerplate in the README to make it cleaner, let me know if this misses anything you'd like to include though. We can of course change it later.
> cut down readme

- src/transformation-components/BuildColumn.tsx
- src/transformation-components/Eval.tsx
- src/transformation-components/Filter.tsx
- src/transformation-components/Sort.tsx
- src/transformation-components/TransformColumn.tsx
- src/ui-components/ExpressionEditor.css
- src/ui-components/MultiAttributeSelector.tsx
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/types.ts
Converted the formula-based transformations to use the `ExpressionEditor` component.
> make filter, transform col, build col, sort use expression editor

- src/Transformation.tsx
- src/transformation-components/BuildColumn.tsx
- src/transformation-components/Compare.tsx
- src/transformation-components/Count.tsx
- src/transformation-components/DifferenceFrom.tsx
- src/transformation-components/Filter.tsx
- src/transformation-components/Flatten.tsx
- src/transformation-components/Fold.tsx
- src/transformation-components/GroupBy.tsx
- src/transformation-components/Join.tsx
- src/transformation-components/PivotLonger.tsx
- src/transformation-components/PivotWider.tsx
- src/transformation-components/SelectAttributes.tsx
- src/transformation-components/Sort.tsx
- src/transformation-components/TransformColumn.tsx
- src/transformation-components/util.ts
- src/ui-components/AttributeSelector.tsx
- src/ui-components/MultiAttributeSelector.tsx
- src/ui-components/TransformationSubmitButtons.tsx
- src/utils/hooks.ts
Changes
- Remove update buttons
- Make created tables always update
We need to figure out what to do with errors. Currently, any errors during updates crash the plugin. We need to figure out how to present errors to the user.
> Make CODAP Flow

- src/Transformation.tsx
- src/transformation-components/Average.tsx
- src/transformation-components/DotProduct.tsx
- src/transformation-components/PolymorphicComponent.tsx
- src/transformation-components/types.ts
- src/transformation-components/util.ts
- src/transformations/average.ts
- src/transformations/dotProduct.ts
- src/ui-components/TransformationSubmitButtons.tsx
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/types.ts
Until the bug on the CODAP side gets fixed, we can't create or update text through the API, so this just uses single-celled tables instead. For dot product, we could also have the user choose which columns to take the dot product of. Right now it takes the dot product of all columns.
> Dot product and average

- src/transformation-components/BuildColumn.tsx
- src/transformation-components/Compare.tsx
- src/transformation-components/Copy.tsx
- src/transformation-components/Count.tsx
- src/transformation-components/DifferenceFrom.tsx
- src/transformation-components/Eval.tsx
- src/transformation-components/Filter.tsx
- src/transformation-components/Flatten.tsx
- src/transformation-components/Fold.tsx
- src/transformation-components/GroupBy.tsx
- src/transformation-components/Join.tsx
- src/transformation-components/PivotLonger.tsx
- src/transformation-components/PivotWider.tsx
- src/transformation-components/SelectAttributes.tsx
- src/transformation-components/Sort.tsx
- src/transformation-components/TransformColumn.tsx
- src/transformations/buildColumn.ts
- src/transformations/compare.ts
- src/transformations/count.ts
- src/transformations/filter.ts
- src/transformations/fold.ts
- src/transformations/groupBy.ts
- src/transformations/join.ts
- src/transformations/pivot.ts
- src/transformations/selectAttributes.ts
- src/transformations/sort.ts
- src/transformations/transformColumn.ts
- src/transformations/util.ts
- src/ui-components/ContextSelector.tsx
- src/utils/codapPhone/error.ts
This updates transformation error messages to have consistent capitalization, somewhat better printing of CODAP values, and simpler handling of setting error messages.
> improve error messages

- src/transformation-components/Average.tsx
- src/transformation-components/DotProduct.tsx
- src/transformations/average.ts
- src/transformations/dotProduct.ts
- src/utils/codapPhone/index.ts
Add attribute selector for dot product so that users can choose which columns to take the dot product of.
> Dot product attribute select

- package-lock.json
- package.json
- src/utils/codapPhone/actions.ts
- src/utils/codapPhone/cache.ts
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/resource.ts
- src/utils/codapPhone/types.ts
- src/utils/codapPhone/util.ts
- Bunch up all the update requests so the UI only gets redrawn when all the changes are done. This removes the flicker and shrinking and growing when columns get added or deleted.
- Also cache records, contexts, and individual cases to avoid making api calls.
> Improve updates

- src/utils/codapPhone/types.ts
> Trigger flow update after sorting

- src/language/parselets.ts
- src/utils/codapPhone/index.ts
Really minor but it seemed like a good idea to get rid of these.
> Fix minor warnings

- src/utils/codapPhone/index.ts
- src/utils/codapPhone/types.ts
Conform to the suggestions made in https://github.com/concord-consortium/codap/pull/390.
> Use new eval and function info endpoints

- src/transformer-components/DataDrivenTransformer.tsx
- src/transformer-components/transformerList.ts
> inputs/outputs -> consumes/produces

- src/index.css
- src/transformer-components/DataDrivenTransformer.tsx
- src/ui-components/ExpressionEditor.css
- src/ui-components/ExpressionEditor.tsx
- src/ui-components/TextArea.tsx
- src/ui-components/TextInput.css
- src/ui-components/TextInput.tsx
- src/ui-components/TransformerSaveButton.css
- src/ui-components/TransformerSaveButton.tsx
- src/utils/codapPhone/index.ts
- Fix font in purpose statement textbox to match rest of UI
- Add proper errors to the save transformer logic
- Make default plugin size larger
- Only render "more info" icon in transformer REPL
> small UI improvements

- src/transformer-components/DataDrivenTransformer.tsx
- src/transformer-components/util.ts
> Add second context in listener dependency

- src/transformers/buildColumn.ts
- src/transformers/filter.ts
- src/transformers/fold.ts
- src/transformers/pivot.ts
- src/transformers/sort.ts
- src/transformers/transformColumn.ts
Fixes #124, and adds slightly more robust checking of text inputs to several transformers by trimming whitespace.
> fix build column empty attr bug, more careful checking for empty inputs

- src/transformers/partition.ts
- src/utils/codapPhone/index.ts
- src/utils/codapPhone/util.ts
- src/utils/transformationDescription.ts
- Remove X emoji from CODAP eval error messages.
- Put quotes around context name in error messages.
> Error message tweaks

- src/transformer-components/DataDrivenTransformer.tsx
- src/ui-components/ContextSelector.tsx
Fixes #169.
This is a similar approach to the one we take in the attribute selector.
> Check if selected context is a valid context

- src/utils/transformationDescription.ts
> Check whether output context has been deleted before adding [fixed]

- src/transformers/fold.ts
Fixes the issue where running aggregators treat missing values as 0.
This is necessary because `Number` returns 0 for any whitespace string. I'm not sure using the previous value in the column is the right choice. Maybe it should be blank. We can discuss in the next meeting.
> Check for missing value in running aggregators

- README.md
Hopefully this can make the project structure make sense to an outsider.
Feel free to go in and change the description as you see fit if I left anything out or could word something better.
> update README and describe project structure

- src/components/ui-components/ExpressionEditor.tsx
- Complete attribute names that have spaces in them with backticks.
- When completing function names, move cursor between the parentheses after completion, just like the CODAP editor does.
> Autocomplete enhancements

- src/components/ui-components/AttributeSelector.tsx
- src/components/ui-components/CollectionSelector.tsx
- src/components/ui-components/ContextSelector.tsx
- src/components/ui-components/MultiAttributeSelector.tsx
- src/components/ui-components/Select.tsx
- src/components/ui-components/TypeSelector.tsx
Added explanations to several UI elements that allow the user to select something from a list.
> add tooltips to several selectors

- src/strings/en/errors.ts
- src/transformers/selectAttributes.ts
> validate mode input for select attributes

- src/lib/codapPhone/index.ts
Stop reverting to the default textbox size on every text update.
> Do not update textbox size

- src/components/ui-components/ExpressionEditor.tsx
- src/lib/codapPhone/index.ts
- src/strings/en/errors.ts
Fixes #207.
Removes all the lookup functions, which are unavailable, from the autocomplete list.
> Fix function completion

- .eslintrc.js
- src/views/REPLView.tsx
- src/views/SavedDefinitionView.tsx
- src/views/util.ts
Resolves #243. 
This also customizes the warning to whether or not you're closing the main plugin window or a saved Transformer.
> Always warn when closing plugin, suggest minimize

- src/components/info-components/AboutInfo.tsx
- src/components/transformer-template/DefinitionCreator.tsx
- src/components/transformer-template/TransformerTemplate.tsx
- src/components/transformer-template/styles/DefinitionCreator.css
- src/transformerList.ts
- src/transformers/partition.ts
- src/transformers/types.ts
- src/views/SavedDefinitionView.tsx
> Fix grammar and editing corrections from #247

- src/transformerList.ts
Fixes #246.
Remove purpose statements from sort and all Transformers without formulas
> Remove unnecessary purpose statements
