package.json, src/reportWebVitals.ts, src/setupTests.ts
On my machine, `npm run format` wasn't targeting nested subdirectories, and adding single quotes around the file pattern globs in `package.json` following the suggestion from https://prettier.io/docs/en/cli.html fixed it.
=> Fix prettier

src/Transformation.tsx, src/language/__tests__/interpret.test.ts, src/language/__tests__/lex.test.ts, src/language/ast.ts, src/language/interpret.ts, src/language/lex.ts, src/language/parse.ts
I realized `row()` should probably be called `attr()` and several other places where we refer to "columns" should be in terms of "attribute" instead, to keep better consistency with the CODAP lingo.
I also updated a few error messages.
=> change `row()` to `attr()`, improve some error messages

src/Transformation.tsx, src/transformation-components/Filter.tsx, src/transformations/filter.ts, src/transformations/types.ts, src/transformations/util.ts, src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts, src/utils/hooks.ts
This adds very preliminary support for multiple transformations, by extracting the functionality of filter out of the UI code. This is meant as a jumping off point and is WIP. 
This defines the notion of a "dataset" as:
```ts
export type DataSet = {
context: DataContext;
records: Record<string, unknown>[];
};
```
and a transformation as something which fulfills the following contract: 
```ts
export interface Transformation {
(dataset: DataSet, extra?: unknown): DataSet;
}
```
That is, a transformation produces a whole new dataset as its output. This allows for transformations that may change not just records but the structure of the collections themselves (adding/deleting attributes, etc). The `extra` is intended to allow for extra information a transformation might need (e.g. in the case …
=> abstract over transformations

src/Transformation.tsx, src/transformation-components/Filter.tsx
This gets rid of the warning when running tests, by using the `defaultValue` property to indicate which `<option>` the selects should have selected by default ("Select a Transformation" and "Select a Data Context"). 
I think this is fine, let me know if there's a better way to remove this warning.
=> switch from using `selected` on options to `defaultValue`

src/Transformation.tsx, src/transformation-components/SelectAttributes.tsx, src/transformations/selectAttributes.ts, src/transformations/util.ts
This transformation (detailed [here](https://github.com/brownplt/B2T2/blob/main/TableAPI.md#overload-33-selectcolumns--t1table--selectorseqcolname---t2table)) allows you to create a new dataset and cherry pick which attributes to include from the original. 
If a collection consists entirely of attributes that were not included in the output, it is removed and its children re-parented.
Currently, the "update" functionality still doesn't work since we need a way of updating data contexts that accounts for structural changes like this.
=> add select attributes

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/transformation-components/TransformColumn.tsx, src/transformations/buildColumn.ts, src/transformations/transformColumn.ts
Adds a build column transformation that allows you to construct new columns by evaluating an expression at every record and putting the result under a new attribute. The user gets to select which collection to put the new column under. 
If a child attribute is referenced when building on a parent collection, the parent cases will just change their grouping based on how the child attribute differentiates between cases that previously had no differentiation at the parent level.
=> add build column

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/transformation-components/TransformColumn.tsx, src/transformations/buildColumn.ts, src/transformations/transformColumn.ts
This is a pretty bare-bones implementation of transform column: just update one attribute's records by evaluating the user's expression in the record's environment. 
We can mess around with this as a starting point and try to get weird behavior that might convince us of how we want this to behave. Right now, using a child attribute to transform a parent is just fine, and will usually end up splitting the previously-grouped parent cases into multiple cases.
You can also screw up formula based attributes pretty bad if you transform a column that formulas depend on. Realistically, I don't know if you'd ever make such a drastic transformation that would make the formula completely useless, so maybe it is good that formulas are left recomputed based on the transformed column.
=> transform column

src/transformations/flatten.ts, src/utils/codapPhone/index.ts
Since every data context we get from CODAP passes through `normalizeDataContext`, its attributes are copied correctly and only include the fields we've defined in our `CodapAttribute` type.
Therefore, any further copying of attributes can simply do a normal copy, rather than having to use the `copyAttrs` functionality in `utils/codapPhone/index.ts`. I've updated flatten to no longer depend on this and removed the export of `copyAttrs`.
=> fix copying of attributes in flatten

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/transformation-components/Compare.tsx, src/transformation-components/Count.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Filter.tsx, src/transformation-components/Flatten.tsx, src/transformation-components/Fold.tsx, src/transformation-components/GroupBy.tsx, src/transformation-components/SelectAttributes.tsx, src/transformation-components/Sort.tsx, src/transformation-components/TransformColumn.tsx, src/transformation-components/util.ts, src/ui-components/AttributeSelector.tsx, src/ui-components/CodapFlowSelect.tsx, src/ui-components/CodapFlowTextArea.tsx, src/ui-components/CodapFlowTextInput.tsx, src/ui-components/ContextSelector.tsx, src/ui-components/TransformationSubmitButtons.tsx, src/ui-components/index.ts, src/utils/codapPhone/index.ts, src/utils/hooks.ts
* Create a set of UI components for common UI elements (dropdown, text input, text area, transformation buttons) and switch over existing `transformation-components` to use the new UI components.
* Factor out repeated behavior from `transformation-components`. Affected behavior is as follows:
* Listening for updates in source context and performing corresponding transformations: `useContextUpdateListenerWithFlowEffect`. This function takes a two context names and calls a callback when the first one updates. See the docstring for more info.
* Deciding whether to update or create a new table and handling errors: `applyNewDataSet`. This function takes a dataset and some other callbacks/state and either makes a new table or updates an existing one, handling errors accordingly.
* Turning a …
=> Standardize component UI and functionality

src/transformations/compare.ts, src/transformations/count.ts, src/transformations/selectAttributes.ts
This implements the fixes noted [here](https://www.notion.so/Copying-values-vs-formulas-08f1a00664034e989e0487dcca63b1ff). 
For count, I also noticed that it wasn't ever counting objects correctly (for instance, Boundaries were always seen as distinct). I updated count to use `JSON.stringify` for now for deep equality but I really do not like this solution. LMK if you all have any ideas.
=> copy values instead of formulas in some transformations

src/transformation-components/Compare.tsx
Quick fix. Right now the compare type selection doesn't show the actual compare type.
=> Fix compare type selection

src/transformation-components/Count.tsx, src/transformations/count.ts, src/transformations/util.ts
This is a new version of count that allows the user to select multiple attributes to count by. It counts the frequency of every tuple of those attributes that is present in the input dataset. For instance, if you want to count the frequency of Sex/Age pairs, you could get the following output:
=> count with multiple attributes

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/transformation-components/Compare.tsx, src/transformation-components/Count.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Filter.tsx, src/transformation-components/Flatten.tsx, src/transformation-components/Fold.tsx, src/transformation-components/GroupBy.tsx, src/transformation-components/SelectAttributes.tsx, src/transformation-components/Sort.tsx, src/transformation-components/TransformColumn.tsx, src/transformation-components/util.ts, src/utils/codapPhone/index.ts
This updates the naming of tables/contexts to use names relevant to the performed transformation, such as "Filter of ____" or "Count of ___".
Note that with this approach names can get pretty unwieldy pretty quickly, if you are heavily composing transformations.
=> name tables relative to transformations

src/transformation-components/Count.tsx, src/transformation-components/PivotLonger.tsx, src/transformation-components/PivotWider.tsx
Pivot / multi-attribute count were developed without the new names ("Pivot of ____") and the multi-attribute select component. This converts them to use those features in uniformity with the other transformations.
=> convert pivots/count to use multi-attribute select and new naming schema

src/transformation-components/util.ts, src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts
This is the finalized context update PR, with the recent merged changes folded in. Now there are reactive updates when things other than data change, such as when the user renames an attribute. These collection updates are done by first adding an empty collection, then deleting all old collections, then adding all the new collections. Since this is more expensive than the usual update (takes longer, more visual flicker), we will check if the collections have changed before performing this kind of update. If only the data has changed, we just delete and insert the data items as before.
A caveat is that when we delete all collections, the table gets shrunk, which feels finicky and is not great user experience. Not sure how to fix this yet.
=> Context update

src/Transformation.tsx, src/transformation-components/Eval.tsx, src/utils/codapPhone/error.ts, src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts
```patch
From 7338da6b9aff3bb5adfef2c14da37fe3e14e76a1 Mon Sep 17 00:00:00 2001
From: Jason Chen <kbtpodifo@gmail.com>
Date: Mon, 31 May 2021 16:12:18 -0400
Subject: [PATCH] Add eval handler for demo
---
.../data_interactive_phone_handler.js         | 26 +++++++++++++++++++
1 file changed, 26 insertions(+)
diff --git a/apps/dg/components/data_interactive/data_interactive_phone_handler.js b/apps/dg/components/data_interactive/data_interactive_phone_handler.js
index 558f3f8c..1f525549 100644
--- a/apps/dg/components/data_interactive/data_interactive_phone_handler.js
+++ b/apps/dg/components/data_interactive/data_interactive_phone_handler.js
@@ -423,6 +423,32 @@ DG.DataInteractivePhoneHandler = SC.Object.extend(
},
handleOneCommand: function (iCmd) {
var result = {success: false};
+
+ …
```
=> Add eval demo

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Fold.tsx, src/transformation-components/TransformColumn.tsx
This just converts a few transformations that were still using text boxes for user input of existing attribute names to now use the attribute selector component.
Also, I changed the fold transformations' naming so that their names appear capitalized in titles (e.g. "Running Sum of People").
=> use attribute selectors instead of text inputs

src/Transformation.tsx, src/transformation-components/BuildColumn.tsx, src/ui-components/CollectionSelector.tsx, src/ui-components/index.ts, src/utils/codapPhone/index.ts, src/utils/hooks.ts
Adds a dropdown selector for collections much like the existing `ContextSelector` and `AttributeSelector`. This is used exclusively in build column at the moment but could be useful in the future. Also fixed up a few names that seemed to be left over from prior copying of code.
=> add a collection selector

src/Transformation.tsx, src/transformation-components/Join.tsx, src/transformations/join.ts
This adds a join transformation that behaves similarly to the drag-and-drop way of joining in CODAP.
CODAP allows you to perform a join by dragging one attribute from a context onto an attribute from another. In effect, it joins _collections_ together by copying attributes from the dragged attribute's collection (what I've called the joining collection) into the dragged-onto attribute's collection (what I've called the base collection). It fills in case data by searching the joining collection for the first case for which the dragged-from and dragged-onto attributes' values match. If no such match is found, the case values for the new attributes are left missing.
CODAP's join effectively mutates the base collection, by literally adding attributes that then use a formula + lookup function …
=> add join transformation

src/transformation-components/BuildColumn.tsx, src/transformation-components/Filter.tsx, src/transformation-components/Sort.tsx, src/transformation-components/TransformColumn.tsx, src/transformations/buildColumn.ts, src/transformations/filter.ts, src/transformations/sort.ts, src/transformations/transformColumn.ts
This updates the following transformations to use the new `evalExpression` functionality: 
- filter
- transform column
- build column
- sort
Note: with sort you may observe some weird behavior due to seemingly numeric attributes evaluating to string values in their language. (For instance, sort by Age will sort by Age _lexicographically_, so you have to use something like `number(Age)` to get the right result). We'll probably want to look into a way of mitigating this behavior.
=> switch to CODAP expression language

src/transformations/count.ts, src/transformations/util.ts, src/ui-components/AttributeSelector.tsx, src/ui-components/CodapFlowSelect.tsx, src/ui-components/CollectionSelector.tsx, src/ui-components/ContextSelector.tsx, src/ui-components/MultiAttributeSelector.tsx, src/utils/codapPhone/index.ts, src/utils/names.ts
This alters `CodapFlowSelect` so that it only displays the option's underlying value if there are multiple options that share the exact same title. I.e., in a situation in which the value is necessary to disambiguate between like titles. This greatly reduces the length of the dropdowns and removes clutter in most situations (when titles are indeed unique).
I also consolidated the "generate unique name" functionality that was required in both codapPhone utils and certain transformations under one function instead of having multiple that effectively do the same thing.
=> improve appearance of names in dropdowns

src/transformation-components/Compare.tsx, src/transformations/__tests__/util.test.js, src/transformations/compare.ts, src/transformations/util.ts, src/utils/__tests__/sets.test.js, src/utils/sets.ts
This adds a new transformation under the compare component that implements the functionality we've talked about with comparing packets.
There are still many many edge cases to work out involving what happens when the two data contexts don't have the same set of attributes, or when two cases are identical besides the decision. Also, I think a better name is in order, but nothing comes to mind.
EDIT: name changed from "decision" to "categorical." The existing categorical diff was renamed to structural.
=> Add "Categorical Compare" transformation

src/transformations/transformColumn.ts
This fixes a bug that occurred when using transform column on a formula-based attribute. If the formula is preserved in the output, then it governs the values and the computed values during the transform are effectively replaced. I updated transform column to always wipe the formula of the transforming attribute.
=> delete formulas when using transform column on formula-based attribute

src/Transformation.tsx, src/transformation-components/Copy.tsx, src/transformations/copy.ts
This adds a transformation that produces an identical copy of the input table. This could be desirable because CODAP doesn't seem to have any native copying feature.
=> add copy transformation

src/transformation-components/BuildColumn.tsx, src/transformation-components/Compare.tsx, src/transformation-components/Copy.tsx, src/transformation-components/Count.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Filter.tsx, src/transformation-components/Flatten.tsx, src/transformation-components/Fold.tsx, src/transformation-components/GroupBy.tsx, src/transformation-components/Join.tsx, src/transformation-components/PivotLonger.tsx, src/transformation-components/PivotWider.tsx, src/transformation-components/SelectAttributes.tsx, src/transformation-components/Sort.tsx, src/transformation-components/TransformColumn.tsx, src/transformation-components/util.ts, src/transformations/buildColumn.ts, src/transformations/count.ts, src/transformations/fold.ts, src/transformations/groupBy.ts, src/transformations/pivot.ts, src/transformations/transformColumn.ts
This updates the naming of fold operations to incorporate the name of the table on which they were computed in their attribute:
The format is now "\<fold type\> of \<attribute\> from \<data context\>". If it detects a long attribute name (one that contains spaces), it will parenthesize the inner attribute.
The attribute `description` property (which appears in a tooltip) is used to provide a full description of the fold that took place. I've also incorporated this `description` property into other transformations that create new attributes or significantly modify them.
=> change fold names + use attribute descriptions

src/Transformation.tsx, src/transformation-components/CombineCases.tsx, src/transformation-components/Compare.tsx, src/transformation-components/Copy.tsx, src/transformation-components/CopySchema.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Eval.tsx, src/transformation-components/Flatten.tsx, src/transformation-components/Fold.tsx, src/transformation-components/Join.tsx, src/transformation-components/PivotWider.tsx, src/transformation-components/PolymorphicComponent.tsx, src/transformation-components/TransformColumn.tsx, src/transformation-components/types.ts, src/transformations/combineCases.ts, src/transformations/copySchema.ts, src/utils/sets.ts
This adds two transformations, "combine cases" and "copy schema", which mirror the `stack` and `empty` methods from the [Pyret tables documentation](https://www.pyret.org/docs/latest/tables.html).
Combine cases builds a table with the combined cases of two tables who share the same attribute set. Copy schema creates a copy of a table, but without any records (just the schema is copied).
With these added, we pretty much cover what I would say are the Pyret table operations that apply to our context. There may be more possibilities in the future with transformations that yield a single value, but for now I think this is good.
=> cover pyret table operations

src/transformation-components/Average.tsx, src/transformation-components/DifferenceFrom.tsx, src/transformation-components/Fold.tsx, src/transformation-components/Join.tsx, src/transformation-components/PivotLonger.tsx, src/transformation-components/TransformColumn.tsx, src/ui-components/AttributeSelector.tsx
This is a WIP to fix the single attribute selectors when saved. They previously weren't appearing as grayed out because the `disabled` prop wasn't getting passed through (this was happening in a few other places too which I've changed). 
However now there's the behavior of attribute selectors not holding their saveData value when they are used in a saved transformation. I logged `saveData` and then `attributeName` from inside the body of the `TransformColumn` component during the creation of a saved transformation and saw this:
Which is suspicious, given it's happening twice and the second time `attributeName` is `null` though it is present in the `saveData`.
Let me know if you have ideas about a fix for this / feel free to commit anything
=> fixing single attribute selectors

.env
This makes it so that when you run `npm start`, it doesn't launch `localhost:3000` in the browser, since we are really never using the plugin as a standalone app.
=> disable browser launch on `npm start`

src/transformation-components/Average.tsx, src/transformation-components/DotProduct.tsx, src/ui-components/MultiAttributeSelector.css
This PR
* adds save data for the dot product transformation
* fixes a graphical issue where disabled buttons in a multi-attribute selector would still highlight on hover and change the cursor type
=> Add save data for dot product and fix graphical issue on multi attribute selector

src/Transformation.tsx, src/transformation-components/Partition.tsx, src/transformation-components/PolymorphicComponent.tsx, src/transformation-components/types.ts, src/transformations/partition.ts, src/utils/codapPhone/index.ts
This adds a partition transformation, which generates separate datasets for all distinct values of a given attribute in an input dataset.
Updates currently work by maintaining which contexts currently exist as a result of the partition, and then updating existing contexts, adding new ones for new distinct values, and deleting contexts that no longer appear in the partition output.
=> add partition

src/Transformation.tsx, src/transformation-components/GenericFold.tsx, src/transformation-components/PolymorphicComponent.tsx, src/transformation-components/types.ts, src/transformations/combineCases.ts, src/transformations/fold.ts, src/transformations/util.ts
Right now, we are having the user supply the name of the accumulator. If we always bind it to something like `acc`, then we might run into name conflicts if a column is also named `acc`. This avoids that but does add some complexity.
This "generic" version is also not very powerful. E.g., you can't write something like running average in it, because the expression language doesn't support tuples, so you can't accumulate multiple values that you can then use to calculate the output.
=> Add generic fold

src/transformations/pivot.ts, src/transformations/util.ts, src/utils/prettyPrint.ts
This makes our CODAP value printer aware of boundary objects (by looking for the property `jsonBoundaryObject` within them) and fixes pivot wider to give a more specific error message when boundary objects are used as attribute names.
This does beg the question of how many ways objects can show up as CODAP values, and it does seem like it's limited to boundary objects and a few others. I did find that using just the identifier `US_county_boundaries` as a formula value, for instance, yields an object that has a map from county names as keys to boundary objects as values, so this may be another kind of object we want to be aware of.
=> better errors for boundary objects

src/transformations/buildColumn.ts, src/transformations/combineCases.ts, src/transformations/copy.ts, src/transformations/copySchema.ts, src/transformations/count.ts, src/transformations/filter.ts, src/transformations/flatten.ts, src/transformations/groupBy.ts, src/transformations/join.ts, src/transformations/partition.ts, src/transformations/selectAttributes.ts, src/transformations/sort.ts, src/transformations/transformColumn.ts, src/transformations/util.ts
Since `array.slice()` only shallow copies the array, we are actually mutating records and collections in some of our transformations, which interacts badly with caching. This PR replaces all slices with actual copies. In the case that we don't mutate the objects, the slices have been removed, since they are misleading.
=> Deep copy collections and attributes in transformations

src/transformation-components/Partition.tsx, src/transformation-components/util.ts, src/utils/codapPhone/index.ts, src/utils/codapPhone/listeners.ts, src/utils/codapPhone/types.ts, src/utils/hooks.ts
This, together with the [CODAP-side patch](https://github.com/stardust66/codap/commit/73212082dd7c6eae8346b6d44ff16217f83c8c03) that adds notifications for deleted contexts, allows us to deactivate any listeners that rely on a context existing when it is destroyed.
I added a notion of "dependencies" to the map from context names to listeners. When listeners are added, you indicate an array of context (or other component) names that identify which contexts must still be valid for the listener to be able to run. When a context is deleted, we remove any listeners on it as well as listeners that depend on it.
This fixes #81.
=> add support for removing listeners after context deletion

src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts
This PR changes over CODAP-phone to use the existing endpoint for creating data interactive instead of the one we added. This allows us to remove the endpoint we added.
=> Use existing DI creation endpoint

src/utils/codapPhone/cache.ts, src/utils/codapPhone/index.ts, src/utils/codapPhone/util.ts
Bug reported in messenger. Cases cache causes issues when attributes get moved, because that does not notify case updates for each individual case, so cached cases are not invalidated properly. This PR invalidates all cases in a context when attributes get moved or deleted.
=> Invalidate cache when attributes get moved

src/transformation-components/transformationList.ts, src/ui-components/AttributeSelector.tsx, src/ui-components/MultiAttributeSelector.tsx, src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts, src/utils/hooks.ts
Fixes #97 and #98. Also removes an extraneous UI component in `Select Attributes`.
@stardust66 I had to include hiding and unhiding attributes as mutating operations to make sure they invalidated the cache. Can you make sure I did everything right? I'm no super familiar with the caching code.
=> Fix attribute selector bugs

src/transformer-components/transformerList.ts, src/transformers/combineCases.ts, src/transformers/copyStructure.ts, src/transformers/fold.ts
This changes difference from to match the [corresponding Pyret function](https://www.pyret.org/docs/latest/tables.html#%28part._tables_difference-from%29), and updates the generated dataset descriptions (for this and plain difference) to better explain what they do.
I also did the following name changes:
- "Copy Schema" --> "Copy Structure" since this seems like a more approachable/understandable term
- In several places in the UI where we mention tables, I changed this to "dataset" to match the others we already changed (dropdowns).
Pick new name for "Running Aggregators"
=> fix difference from, name changes

src/utils/codapPhone/listeners.ts
This makes update listeners execute sequentially, which actually speeds up data fetching. Previously, since the update functions fire off data fetching requests before any data is returned, the same data is fetched multiple times, not making use of our cache. Now, each data fetch waits for the previous one to finish, which means if the same piece of data is fetched multiple times, it will be in the cache by the second fetch.
=> Speed up updates

src/transformer-components/DataDrivenTransformer.tsx, src/transformer-components/transformerList.ts
Fixes #103 by allowing the attribute/collection selectors in a data driven transformation to target a custom context dropdown.
=> Fix pivot wider

src/index.css, src/transformer-components/DataDrivenTransformer.tsx, src/ui-components/TransformerSaveButton.tsx
Instead of using `h3` for spacing, we use divs with the class `input-group`, so that elements can be spaced even when there's no title.
=> Minor style edits

src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts, src/utils/codapPhone/util.ts
Fixes #109. Makes `CodapAttribute` type less restrictive. Now, attributes do not need to be numeric to have the `precision` or `unit` properties, which better reflects what the CODAP UI allows. In addition, the type can also be "qualitative", "date", etc., which are options in the type dropdown in the CODAP UI. These options were not in the API documentation, but do have an effect on the UI. For example, the "qualitative" type turns attributes into horizontal bars, like
so we should respect them.
=> Fix attribute copying

src/transformers/compare.ts, src/transformers/fold.ts, src/transformers/groupBy.ts, src/transformers/join.ts, src/transformers/pivot.ts, src/transformers/util.ts, src/utils/codapPhone/index.ts, src/utils/names.ts
This goes back and patches some uses of generated names that weren't ensuring uniqueness. 
I also updated the centralized unique naming function to use `{n}` instead of `(n)` (not ideal, but `(n)` is interpreted as specifying a unit and so won't end up part of the attribute name. And it doesn't like `[n]` for data contexts for some reason).
=> ensure all transformations avoid name collisions

src/App.tsx, src/utils/codapPhone/index.ts
Fixes #110. When opening a new file with `Transformers`, it should still be resized to the default dimensions. However, if you open a CODAP file that contains `Transformers`, it will stay at its current size.
Also added a useEffect hook to stop initialization logic in `App` from being fired multiple times.
=> Don't resize plugin to default dimensions when opening existing file

src/transformers/util.ts
This adds support for recognizing CODAP color values when we go to format colors for printing. For instance, this is used in the titles of partitioned datasets:
It also comes up in error messages:
I figure it's good to expose the underlying hex/rgb/rgba color values--in the event the user didn't create it themselves and doesn't understand it, they'll still see "color" and know it was a color, and in the event they did create it of their own accord, knowing the color values might provide critical info (I prefer this to just showing "a color").
=> recognize color values when formatting

src/transformers/partition.ts
This fixes a bug that was causing the data context name used in partitioned table titles/descriptions to be the actual name and not the title (unlike all the other transformers).
I've also modified the names of output tables in partition so that the values are nearer to the front of the name--however I didn't really find a non-awkward way to have the name start directly with the value. Let me know what you all think of this "{attribute} = {value} in {dataset}" naming convention.
=> fix partition naming bug and make partitioned values clearer

src/transformers/compare.ts, src/utils/colors.ts
Now when performing a numeric compare, the saturation of the colors is proportional to the magnitude of the difference. Ideally we could also solve #125 with this PR, but I'm not sure what colors to use besides red and green.
=> Add color gradation to numeric compare

src/transformer-components/DataDrivenTransformer.tsx, src/transformer-components/SavedTransformerView.css, src/transformer-components/SavedTransformerView.tsx, src/transformer-components/TransformerREPLView.tsx, src/transformer-components/TransformerRenderer.tsx, src/transformer-components/TransformerViews.css, src/ui-components/ExpressionEditor.tsx, src/utils/codapPhone/index.ts
This adds support for editing transformers that have already been saved. You are able to edit any of the inputs to the transformer, but not its name/purpose statement.
You can edit by clicking the Edit button (seen below), at which point disabled inputs will become enabled. The button toggles whether or not inputs are disabled.
=> allow editing of saved transformers

src/transformer-components/DataDrivenTransformer.tsx, src/transformer-components/TransformerREPLView.tsx, src/transformers/partition.ts, src/ui-components/TransformerSaveButton.tsx, src/utils/codapPhone/index.ts, src/utils/codapPhone/listeners.ts, src/utils/codapPhone/types.ts
This PR adds the ability to use the CODAP undo button to delete tables that have just been created by a transformer application. At present, this is the only undoable functionality.
If the user takes certain actions that are hard to undo/redo (like creating/deleting tables), CODAP clear it's undo/redo stack and start over (the undo/redo buttons will be grayed out). CODAP informs us of this so we can also clear the plugins internal undo/redo stack that we're tracking.
Since all our undo functionality involves deleting tables, the user will only ever be able to undo one transformer application before CODAP clears its undo functionality. This PR implements the following hack to get around that: if CODAP tells us to clear the undo stack but we still have undoable actions left, instead of …
=> Add undo functionality for transformer application

src/transformers/__tests__/data.ts, src/transformers/buildColumn.ts, src/transformers/filter.ts, src/transformers/fold.ts, src/transformers/sort.ts, src/transformers/transformColumn.ts, src/utils/codapPhone/index.ts
This PR modifies all transformers that require evaluating a formula to accept a function as a parameter that implements that evaluation logic.
The existing CODAP phone `evalExpression` function is used as a default parameter, but the `transformers/__tests__/data.ts` file includes a `jsEvalFormula` function that can be passed instead to use the js `eval` function as a mock for the CODAP engine.
The tests that actually use this functionality aren't included here. I have them on a separate branch. However, I've also included some additional testing datasets and some changes to the existing test functions.
=> Parameterize formula evaluater in transformers that use formulas

src/transformers/types.ts, src/transformers/util.ts
This uses the `NAME` property that some boundary objects have to add further identifying info when printing a boundary, instead of just "a boundary". This is particularly useful in Partition dataset headers. Now it will print, for instance, "a boundary (Colorado)".
=> use boundary name in value printing when possible

src/transformer-components/transformerList.ts, src/transformers/dotProduct.ts, src/transformers/mean.ts, src/transformers/median.ts, src/transformers/mode.ts, src/transformers/standardDeviation.ts, src/transformers/sumProduct.ts, src/transformers/util.ts
This renames "Average" --> "Mean", and adds three new single-value transformers: Median, Mode, and Standard Deviation.
At the moment, all of these error on a dataset with no records, as well as if non-numeric values are given.
Please look over these and let me know if there are any edge cases you think aren't handled correctly.
=> add median, mode, std deviation

src/transformers/partition.ts
This warns for first applying a partition that will yield no datasets--but does not warn if you apply an update that will cause this situation (i.e. deleting all input cases)
=> warn on partition creating 0 datasets

src/transformer-components/util.ts, src/transformers/buildColumn.ts, src/transformers/combineCases.ts, src/transformers/compare.ts, src/transformers/copy.ts, src/transformers/copyStructure.ts, src/transformers/count.ts, src/transformers/filter.ts, src/transformers/flatten.ts, src/transformers/fold.ts, src/transformers/groupBy.ts, src/transformers/join.ts, src/transformers/mean.ts, src/transformers/median.ts, src/transformers/mode.ts, src/transformers/partition.ts, src/transformers/pivot.ts, src/transformers/selectAttributes.ts, src/transformers/sort.ts, src/transformers/standardDeviation.ts, src/transformers/sumProduct.ts, src/transformers/transformColumn.ts
This switches to dataset titles of the form:
- `Transformer(Dataset)` for transformers whose only parameter is a dataset (or 2)
- `Transformer(Dataset, ...)` for transformers which have other parameters (attributes, formulas, etc). The `...` indicates "more parameters went into this transformer, but you should check the description to read about them"
- something else for special cases.
Special cases include Partition, which creates multiple datasets and therefore seems to need something that differentiates its output datasets by their titles. Also, the single value transformers incorporate the attribute(s) they are computed over, because there is no "description" attached to text components.
Example:
=> use function application syntax in dataset titles

src/transformer-components/DataDrivenTransformer.tsx, src/transformer-components/transformerList.ts, src/transformers/mode.ts, src/transformers/types.ts, src/transformers/util.ts, src/utils/transformationDescription.ts
This adds support for a single-value transformer producing a list of numbers, and applies it to the Mode transformer, which now produces all the mode values of the given attribute.
=> allow multiple values in mode

src/transformers/count.ts, src/transformers/fold.ts, src/transformers/groupBy.ts, src/transformers/join.ts, src/transformers/mean.ts, src/transformers/median.ts, src/transformers/mode.ts, src/transformers/partition.ts, src/transformers/pivot.ts, src/transformers/selectAttributes.ts, src/transformers/standardDeviation.ts, src/transformers/sumProduct.ts, src/transformers/transformColumn.ts, src/transformers/util.ts
This adds a mechanism for ensuring that when a transformer takes a dataset and an attribute(s) from that dataset, we can check that the attribute exists within the dataset (by searching collections).
Previously, "Invalid attribute" errors were mostly being detected when we were processing a row and found that the given attribute was `undefined` for that row. We later discovered that rows can be `undefined` for an attribute that is indeed part of the dataset (see #144 and #148). Relying on row processing to detect these errors was brittle because 1) if there are no rows, attribute errors wouldn't be detected, and 2) the above situation, in which an attribute is actually valid but `undefined` in rows.
This checks attributes separately from handling of undefined values in rows. This PR also …
=> validate attributes in a uniform way

src/transformers/fold.ts
This removes the dataset name from running aggregator names, as was brought up in #154. It also gives Difference From a more useful tooltip.
=> name changes for running aggregators

src/utils/codapPhone/index.ts, src/utils/codapPhone/types.ts, src/utils/transformationDescription.ts
This PR adds to the context deletion listener to make sure that when a table is deleted all it's output tables get the string `[fixed]` appended to their title.
Notably, this title change does not flow through to further tables, so you can get the following scenario.
How do we think this case should be handled? Should we propagate the `[fixed]` notification to further tables, so we get `Copy(Copy(People)) [fixed]`, or should we propagate the new table name so we get `Copy(Copy(People) [fixed])`?
=> Show `[fixed]` labels on table with deleted inputs

src/transformer-components/AboutInfo.tsx, src/transformer-components/DataDrivenTransformer.tsx, src/transformer-components/TransformerInfo.css, src/transformer-components/TransformerInfo.tsx, src/transformer-components/transformerList.ts
This updates the inline docs in the popovers to be consistent with the documentation found [here](https://docs.google.com/document/d/1NZA9gxtu6jD3M-5SQyx0tvV2N5qYKMgRm1XUwMnLgJU/edit#heading=h.1wp8of2gw3s4) (which was reviewed by Emmanuel & co). 
There is also now a "More Info" link which takes you to the particular part of that documentation which details the transformer you are looking at. In particular, the draw of standalone docs is that they allow for more space so there are examples with images.
=> update inline docs to reflect/link to standalone docs

src/transformer-components/TransformerREPLView.tsx
Adds an "Importer" button that spawns the sheets importer.
On localhost CODAP the importer plugin doesn't work. I suspect it's because it's not hosted locally. Can we try and deploy this and see if this works? Then we can send the link.
=> Add importer button

src/transformers/util.ts
Now we get nicer errors with dates like this:
=> add support for recognizing dates as CODAP values

src/ui-components/Error.css
=> Break words when wrapping error messages

.eslintrc.js, package-lock.json, package.json, src/components/info-components/AboutInfo.tsx, src/components/info-components/TransformerInfo.tsx, src/components/transformer-template/TransformerRenderer.tsx, src/components/transformer-template/TransformerTemplate.tsx, src/components/ui-components/styles/ExpressionEditor.css, src/views/REPLView.tsx, src/views/styles/REPLView.css
This PR adds a new transformer selector (using the `react-select` library) that allows searching for selectors by typing.
I know that this behavior exists with native dropdowns on most browsers, but I'm not sure most people know about, and I think the list of transformers is long enough that it becomes a pain to scroll through it each time.
Unfortunately, the new dropdown is quite a bit bigger, so I had to reorganize the "about" and "info" buttons accordingly.
=> Improve transformer selector

src/components/transformer-template/styles/DefinitionCreator.css
Apparently Firefox wanted us to be explicit about the font-size in the purpose statement. Now the sizes are consistent between the name/purpose statement inputs across browsers.
=> fix font difference in purpose statement on firefox

src/components/ui-components/ContextSelector.tsx
Closes #136.
This is implemented as part of `ContextSelector`.
=> Automatically select context if it is the only one

src/lib/codapPhone/index.ts, src/lib/codapPhone/types.ts, src/transformers/__tests__/data.ts, src/transformers/__tests__/editableCopy.test.ts, src/transformers/types.ts, src/transformers/util.ts
Uses the `preventReorg` property on data contexts to set/unset attribute draggability as part of the immutability of output tables produced by transformers.
Addresses #185.
=> use `preventReorg` to make output dataset attributes non-draggable

src/components/transformer-template/TransformerTemplate.tsx, src/components/ui-components/TypeSelector.tsx, src/transformerList.ts
This PR adds functionality that lets the type selector take a single value instead of a list of options. This will display the value as a raw string instead of a dropdown. It also adds `Context:` before the dropdowns to give the user more instruction.
=> Update type contract UI

src/components/info-components/AboutInfo.tsx, src/views/REPLView.tsx
- Rename "Transformer Type" to "Transformer"
- Remove "the" from attribution
=> Rename label, change wording

src/App.css, src/App.tsx, src/components/transformer-template/TransformerTemplate.tsx, src/components/transformer-template/styles/TransformerTemplate.css
I noticed that applying some transformers (especially if the table had boundaries) took long enough that it felt like nothing was happening for a moment when you hit `apply transformer`. I've added a loading spinner to help fix that. I opted for a loading spinner that appears on top of the button as opposed to the side to really reinforce the idea that the button is disabled while transformers are being applied. If you have alternate suggestions for stylng feel free to suggest them.
=> Add loading indicator to apply transformer button

src/lib/codapPhone/index.ts, src/lib/codapPhone/types.ts, src/views/REPLView.tsx, src/views/SavedDefinitionView.tsx
Whenever `setErrMsg` is called with a non-empty error message, an api request is sent to select the plugin. This causes it to be brought to the front of the workspace so the user is made aware an error occured.
=> Bring plugin to front when an error occurs

src/transformerStore/index.ts
Deletes the functionality for adding the [fixed] label to outputs that have no way of updating.
=> removed [fixed] label

src/lib/codapPhone/index.ts
Fixes #132, I think. I can't reproduce the erroring behavior mentioned there and I think it may be because our UI selectors have since gotten smarter about dealing with deleted datasets.
@stardust66, does this do everything necessary to invalidate the cache for the deleted context? Is there anything else I'm missing?
=> invalidate cache for deleted contexts

src/components/transformer-template/TransformerTemplate.tsx, src/lib/codapPhone/index.ts, src/lib/codapPhone/listeners.ts, src/lib/codapPhone/types.ts, src/transformerStore/index.ts
This addresses part of #186 -- the unhandled rejection part where we tried to get a text component as a data context.
I also made it so that new updates cause the error message to clear before the update happens. That way, if an update error is fixed, the flowing through of the update will remove the error message.
=> fixed updating errors for text outputs causing crash

src/components/info-components/AboutInfo.tsx
This tries out using an `IconButton` for the "About" button:
| Button      | IconButton |
| ----------- | ----------- |
| ![button](https://user-images.githubusercontent.com/13399527/128224097-9b467912-55c0-4b9c-bb16-dba6c7d12a9b.png) | ![about](https://user-images.githubusercontent.com/13399527/128223801-48c425b2-6cca-459a-8b8c-e5db31a7506f.png) |
I do like that this reduces the size of the button but it has the disadvantage of being quite similar to the (i) icon and right above it. Which do you all prefer?
=> use icon for about button

src/components/transformer-template/TransformerTemplate.tsx, src/transformerList.ts
Let me know thoughts on the specific wording of the prompt. Right now it is "Keep all rows that satisfy:"
We can also use this prompt feature for other expression editor transformers. I think Sort might benefit from it, but I'm not sure the right wording to use.
=> add a prompt to the filter expression

src/components/transformer-template/DefinitionCreator.tsx
This should solve our saved transformer issue by adding the transform parameter to the full url, not just the origin part.
=> Do not assume plugin is at url root

src/lib/codapPhone/index.ts
This fixes a bug where if you do a transform on an attribute and that attribute is renamed, the update will not error because it still sees the old name for the attribute in the cache.
=> Invalid cache on attribute rename

src/lib/codapPhone/index.ts, src/transformers/partition.ts
This fixes #95, at least for partition. However, I have no idea why. It does so by making partition updates synchronous. As a consequence this makes partition updates a lot slower.
I also threw in a more specific error if the response from CODAP comes back `undefined` in `updateContextWithDataSet`, so that we'll at least get something better than responses is not iterable.
I'm not sure what we want to do about this since I'm the only one who can reproduce.
=> make partition updates synchronous

src/lib/codapPhone/index.ts
This adds checks to every `response` in a call to iframe-phone to ensure it is not `undefined` before using it. In the `undefined` case it gives a more informative error message about an invalid response than what would be raised if we just used the value.
=> check all responses from iframe-phone

src/components/transformer-template/TransformerTemplate.tsx, src/lib/codapPhone/actions.ts, src/lib/codapPhone/index.ts, src/lib/codapPhone/listeners.ts, src/lib/codapPhone/types.ts, src/lib/codapPhone/util.ts, src/transformerList.ts, src/transformerStore/index.ts, src/transformerStore/util.ts, src/transformers/partition.ts, src/views/REPLView.tsx, src/views/SavedDefinitionView.tsx
Add `useEditedOutputs`, which keeps track of the contexts that have had their titles manually edited, and use this information to decide whether to include updated titles in normal transformer updates.
=> Flow title updates

src/components/info-components/AboutInfo.tsx, src/lib/codapPhone/index.ts, src/views/REPLView.tsx, src/views/SavedDefinitionView.tsx, src/views/styles/SavedDefinitionView.css, src/views/util.ts
This PR disables the CODAP close button for the plugin component and adds a custom close button that asks the user to confirm if they close the plugin while there are any `activeTransformations`. This also applies to saved transformers
=> Disable CODAP close button and add custom close button

src/components/transformer-template/TransformerTemplate.tsx, src/components/ui-components/TypeSelector.tsx, src/lib/utils/typeChecking.ts, src/strings/en/errors.ts, src/transformerList.ts, src/transformers/__tests__/buildAttribute.test.ts, src/transformers/__tests__/filter.test.ts, src/transformers/__tests__/sort.test.ts, src/transformers/__tests__/transformAttribute.test.ts, src/transformers/types.ts
Fixes #223. 
Worth noting that one reason we may have stuck with lowercase types is that it matches the uses of type names in the CODAP language (see functions `number()` or `boolean()` for instance).
=> Capitalize type names in contracts

src/components/ui-components/ExpressionEditor.tsx
Fixes #226.
I figure we should hold off on changing "key expression" until we've resolved the question of sort sorting by an expression or by an attribute.
=> rename 'formula expression' to 'expression'

src/transformerList.ts
Addresses the wording inconsistencies mentioned in #231 among other places.
Branched off of `sort` because the changes are dependent on the new Sort that has two variants.
=> Use consistent language for formula titles

src/components/transformer-template/TransformerTemplate.tsx, src/components/ui-components/Select.tsx, src/lib/utils/__tests__/typeChecking.test.ts, src/lib/utils/typeChecking.ts, src/strings/en/errors.ts, src/transformerList.ts, src/transformers/__tests__/sort.test.ts, src/transformers/sort.ts
Resolves #224.
Changes:
- Add toggle component which is a dropdown where each option hides certain other components.
- Add sorting by attribute.
TODO:
=> Support two kinds of sort

src/components/transformer-template/TransformerTemplate.tsx, src/components/ui-components/ExpressionEditor.tsx, src/transformerList.ts
Addresses a comment from #239.
This allows us to specify custom placeholders for expression editors, with the goal of helping students think about what a potential expression might look like for a given transformer.
I am not at all set on the placeholders I've chosen so far, they are just a proof-of-concept. Some things to consider:
- How do we give example expressions in a way that doesn't confuse the student? Currently I've included attribute names that are made-up, and so entering verbatim what's in the placeholder will cause an error (unless they're on a dataset that happens to have that attribute name), but is this necessarily an issue?
- Is including text like "e.g." helpful? Or it would it be better blank or with something else?
Example:
=> Add customizable placeholder text for formula expression editors

src/components/transformer-template/DefinitionCreator.tsx, src/views/SavedDefinitionView.tsx
Adds an error message when trying to save a transformer with the same name as an existing transformer
=> Prevent saving transformers with duplicate names

src/components/transformer-template/DefinitionCreator.tsx, src/components/transformer-template/TransformerTemplate.tsx, src/components/transformer-template/styles/DefinitionCreator.css, src/components/transformer-template/styles/TransformerTemplate.css, src/components/ui-components/Select.tsx, src/lib/codapPhone/index.ts, src/lib/utils/__tests__/typeChecking.test.ts, src/lib/utils/typeChecking.ts, src/strings/en/errors.ts, src/transformerList.ts, src/transformers/__tests__/sort.test.ts, src/transformers/sort.ts, src/views/SavedDefinitionView.tsx
Resolves #231.
Transformer with formula:
Transformer without formula:
Things to tweak:
- Should purpose statement have its own heading or be included in the expression input?
- We could remove the toggle for the save button since it's just a single button now.
Edit: Updated screenshots.
=> Name purpose UI

src/components/transformer-template/TransformerTemplate.tsx
Fixes #250. See #247 for screenshot of the issue.
=> Ignore name component when rendering saved transformer

src/transformerList.ts
In accordance with #247, this updates the placeholder Transformer name text for Reduce to match the placeholder text for its expressions (which suggest a running sum of an Age attribute).
=> Fix Reduce name placeholder
